create table if not exists persons (
	id text primary key,
	nombre text not null,
	telefono text,
	correo_electronico text unique,
	direccion text,
	referencias text
);

create table if not exists shipments (
	id_envio bigint generated by default as identity primary key,
	sender_id text not null,
	recipient_id text not null,
	tipo_servicio text not null,
	nivel_prioridad integer not null default 3,
	codigo_rastreo text not null unique,
	estado_actual text not null,
	fecha_envio date not null,
	fecha_estimada date,
	fecha_actualizacion date,
	costo_total numeric(12,2) not null default 0,
	instrucciones_envio text,
	constraint fk_shipments_sender foreign key (sender_id) references persons(id) on update cascade on delete restrict,
	constraint fk_shipments_recipient foreign key (recipient_id) references persons(id) on update cascade on delete restrict,
	constraint chk_nivel_prioridad check (nivel_prioridad between 1 and 5),
	constraint chk_costo_total check (costo_total >= 0)
);

create table if not exists packages (
	id_paquete bigint generated by default as identity primary key,
	shipment_id bigint not null,
	peso numeric(10,2) not null,
	largo numeric(10,2),
	ancho numeric(10,2),
	alto numeric(10,2),
	descripcion text,
	constraint fk_packages_shipment foreign key (shipment_id) references shipments(id_envio) on update cascade on delete cascade,
	constraint chk_peso check (peso > 0)
);

create table if not exists logistic_events (
	id_evento bigint generated by default as identity primary key,
	shipment_id bigint not null,
	tipo_evento text not null,
	estado_resultante text not null,
	ubicacion text,
	observacion text,
	fecha_evento timestamp not null,
	constraint fk_logistic_events_shipment foreign key (shipment_id) references shipments(id_envio) on update cascade on delete cascade
);

create index if not exists idx_shipments_sender_id on shipments(sender_id);
create index if not exists idx_shipments_recipient_id on shipments(recipient_id);
create index if not exists idx_packages_shipment_id on packages(shipment_id);
create index if not exists idx_logistic_events_shipment_id on logistic_events(shipment_id);
